name: Deploy VRWEB to GitHub Pages
on:
  push:
    branches:
      - main
jobs:
  deploy:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3
        
      - name: List directory structure
        run: find . -type f -not -path "*/\.*" -not -path "*/node_modules/*" | sort
        
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: WEB  # Deploy trực tiếp từ thư mục WEB chứa Unity WebGL build
          branch: gh-pages
          token: ${{ secrets.GITHUB_TOKEN }}
          clean: true
